# Generated by Django 4.1.4 on 2023-08-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0022_wishlist_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="devedu.userprofile",
            ),
        ),
    ]
