# Generated by Django 4.1.4 on 2023-08-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0023_session_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="Session", new_name="CourseSession",),
    ]
