# Generated by Django 4.1.4 on 2023-08-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0024_rename_session_coursesession"),
    ]

    operations = [
        migrations.RemoveField(model_name="coursesession", name="course",),
        migrations.AddField(
            model_name="coursesession",
            name="course",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="session_course", to="devedu.course"
            ),
        ),
    ]
