# Generated by Django 4.1.4 on 2023-08-29 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0025_remove_coursesession_course_coursesession_course"),
    ]

    operations = [
        migrations.RemoveField(model_name="coursesession", name="course",),
        migrations.AddField(
            model_name="coursesession",
            name="course",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_course",
                to="devedu.course",
            ),
        ),
    ]
