# Generated by Django 4.1.4 on 2023-08-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0027_remove_coursesession_course_coursesessionmiddle"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesession",
            name="current_serial",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
